### ISSUE TITLE
Options>Set Permissions  Use of "Test Permission" button

### ISSUE THREAD

**Issue by Jinumol** [daneshka/RayBPMS#23]
![image](https://user-images.githubusercontent.com/35736988/35303602-8a6f8d56-0060-11e8-8f56-08a8a940c002.png)

I dint understand the use of Test Permission button.

**Comment by al1b** [comment]
`Test Permission` button should remove from this form. If you view the form in Persian you won't see that button.

**Comment by daneshka** [comment]
This issue was moved to Interfacing/BPMS#23
